version: '3.1'

services:
  zoo1:
    image: zookeeper:3.5.5
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181

  consul:
    hostname: consul
    container_name: consul
    image: consul:1.5.3
    restart: always
    environment:
      - CONSUL_LOCAL_CONFIG={"disable_update_check":true}
    entrypoint:
      - consul
      - agent
      - -server
      - -bootstrap
      - -data-dir=/data
      - -bind={{ GetInterfaceIP "eth0" }}
      - -client=0.0.0.0
      - -ui
    ports:
      - 8500:8500  # protect this in the real world!

  db:
    image: postgres:postgres:11.8-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
